### ISSUE TITLE
Acknowledging Messages 

### ISSUE THREAD

**Issue by DeadlySurgeon** [Bios-Marcel/discordgo#3]
How do I acknowledge that I received a message using this fork?

**Comment by Bios-Marcel** [comment]
https://github.com/Bios-Marcel/cordless/blob/master/readstate/readmarkers.go#L96

**Comment by DeadlySurgeon** [comment]
Thank you <3

**Comment by Bios-Marcel** [comment]
Why do you even use my fork? ^^

**Comment by DeadlySurgeon** [comment]
The main fork doesn't have user authentication, does it?

**Comment by Bios-Marcel** [comment]
Correct, but mine is half-assed and doesn't have proper documentation. I really don't recommend relying on it too much.

**Comment by DeadlySurgeon** [comment]
Well, it most certainly isn't the only one I have to deal with like that c:

My main use case is for scraping messages off of a specific server as they came in so I could get alerts. I'm just using this library for receiving the message events and then throwing them into kafka.

**Comment by Bios-Marcel** [comment]
I see. Welp, good luck then. If you have any issues, you'll probably have to make a PR though ^^

**Comment by DeadlySurgeon** [comment]
Absolutely! Thank you for your work here though. :D
